export const API_VERSION = 'v1';
export const API_PREFIX = 'internal';

export const SERVICE_KEY_HEADER = 'X-Service-Key';
export const SERVICE_ID_HEADER = 'X-Service-Id';

export const ERROR_CODES = {
  // Authentication errors
  INVALID_SERVICE_KEY: 'AUTH001',
  SERVICE_KEY_EXPIRED: 'AUTH002',
  SERVICE_KEY_INACTIVE: 'AUTH003',
  RATE_LIMIT_EXCEEDED: 'AUTH004',
  
  // Organization errors
  ORGANIZATION_NOT_FOUND: 'ORG001',
  ORGANIZATION_SUSPENDED: 'ORG002',
  ORGANIZATION_DELETED: 'ORG003',
  
  // Validation errors
  VALIDATION_FAILED: 'VAL001',
  INVALID_REQUEST: 'VAL002',
  
  // System errors
  INTERNAL_ERROR: 'SYS001',
  DATABASE_ERROR: 'SYS002',
  EXTERNAL_SERVICE_ERROR: 'SYS003',
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;